# netlify.toml

[build]
  # Comando que Netlify ejecuta para compilar tu aplicación Vue/Vite
  command = "npm run build"
  # Directorio donde Vite coloca los archivos finales
  publish = "dist"

# Configuración para forzar el tipo MIME para los assets de JavaScript y Módulos
# Esto corrige el error 'text/vnd.trolltech.linguist'
[[headers]]
  # Aplica a todos los archivos estáticos generados (generalmente en /assets)
  for = "/assets/*"
  [headers.values]
    # Establece el tipo MIME correcto
    Content-Type = "application/javascript"

[[headers]]
  # Esto también aplica a cualquier otro archivo con extensión JS (como main.ts compilado)
  for = "*.js"
  [headers.values]
 main
    Content-Type = "application/javascript"
    Content-Type = "application/javascript"
    main
